import 'package:hive/hive.dart';

part 'transaction.g.dart'; // generated by build_runner (hive_generator)

/// Core transaction types we detect from M-Pesa SMS.
@HiveType(typeId: 0)
enum TransactionType {
  @HiveField(0)
  received,
  @HiveField(1)
  sent,
  @HiveField(2)
  paybill,
  @HiveField(3)
  buyGoods,
  @HiveField(4)
  withdraw,
  @HiveField(5)
  deposit,
  @HiveField(6)
  airtime,
  @HiveField(7)
  fuliza,
  @HiveField(8)
  reversal,
  @HiveField(9)
  unknown,
}

/// Spending categories used for budgeting + insights.
@HiveType(typeId: 1)
enum Category {
  @HiveField(0)
  food,
  @HiveField(1)
  transport,
  @HiveField(2)
  rent,
  @HiveField(3)
  airtime,
  @HiveField(4)
  shopping,
  @HiveField(5)
  bills,
  @HiveField(6)
  entertainment,
  @HiveField(7)
  savings,
  @HiveField(8)
  health,
  @HiveField(9)
  education,
  @HiveField(10)
  income,
  @HiveField(11)
  transfer,
  @HiveField(12)
  uncategorized,
}

@HiveType(typeId: 2)
class MpesaTransaction extends HiveObject {
  /// The M-Pesa transaction code, e.g. "QFT2X9K1AB". Used as a natural
  /// de-duplication key so re-scanning the SMS inbox never creates dupes.
  @HiveField(0)
  final String transactionId;

  @HiveField(1)
  final double amount;

  @HiveField(2)
  final TransactionType type;

  @HiveField(3)
  final String counterparty; // sender/recipient name or paybill/till name

  @HiveField(4)
  final String? counterpartyNumber;

  @HiveField(5)
  final DateTime date;

  @HiveField(6)
  final double? balanceAfter;

  @HiveField(7)
  final double? transactionCost;

  @HiveField(8)
  Category category;

  @HiveField(9)
  final String rawSms;

  @HiveField(10)
  final String accountLabel; // for multi-SIM / multi-line support

  @HiveField(11)
  bool isFlaggedAnomaly;

  @HiveField(12)
  String? receiptImagePath;

  MpesaTransaction({
    required this.transactionId,
    required this.amount,
    required this.type,
    required this.counterparty,
    this.counterpartyNumber,
    required this.date,
    this.balanceAfter,
    this.transactionCost,
    this.category = Category.uncategorized,
    required this.rawSms,
    this.accountLabel = 'Default',
    this.isFlaggedAnomaly = false,
    this.receiptImagePath,
  });

  bool get isExpense => [
        TransactionType.sent,
        TransactionType.paybill,
        TransactionType.buyGoods,
        TransactionType.withdraw,
        TransactionType.airtime,
        TransactionType.fuliza,
      ].contains(type);

  bool get isIncome =>
      type == TransactionType.received || type == TransactionType.deposit;
}
